interface exit {
  /// Exit the current instance and any linked instances.
  exit: func(status: result);

  /// Exit the current instance and any linked instances, reporting the
  /// specified status code to the host.
  @unstable(feature = exit-with-code)
  exit-with-code: func(status-code: u8);
}
